# add Cargo.toml so that vscode rust-analyzer can detect main files

[package]
name = "practice"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "template"
path = "misc/templates/main.rs"

[[bin]]
name = "cses-2189"
path = "cses/geometry/task2189/main.rs"

[[bin]]
name = "cses-2138-reachable-nodes"
path = "cses/advanced_techniques/task2138-reachable-nodes/main.rs"

[[bin]]
name = "abc260-a"
path = "atcoder/abc260/a/main.rs"

[[bin]]
name = "abc260-b"
path = "atcoder/abc260/b/main.rs"

[[bin]]
name = "abc260-d"
path = "atcoder/abc260/d/main.rs"

[[bin]]
name = "abc260-e"
path = "atcoder/abc260/e/main.rs"

[[bin]]
name = "abc261-a"
path = "atcoder/abc261/a/main.rs"

[[bin]]
name = "abc261-b"
path = "atcoder/abc261/b/main.rs"

[[bin]]
name = "abc261-c"
path = "atcoder/abc261/c/main.rs"
